name: danger
on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Danger JS Action
        run: npx danger ci
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
